### ISSUE TITLE
"Get Content" window: getting stuck on ru.wikipedia and other items

### ISSUE THREAD

**Issue by aleksejrs** [kiwix/overview#1]
Sometimes I open Russian Wikipedia or some other zim, and then cannot open a different zim: the zim currently open loads every time for many attempts.  Kiwix 2.2 on Android.  I usually have no problem with the middle of the screen, but have had this one with Kiwix since the beginning (one to one-and-half years).

**Comment by kelson42** [comment]
No clue what is going one here. @mhutti1 any idea?
Maybe you could try to see if the problem still appear in this (still unpublished) version of Kiwix for Android https://download.kiwix.org/bin/android/2.3/

**Comment by aleksejrs** [comment]
I can't install it (the installation process ends with "App was not installed").  It seems that my smartphone has an ARMv7 processor.

**Comment by kelson42** [comment]
@aleksejrs Have you tried with both kiwix-2.3_armeabi.apk and kiwix-2.3_arm64-v8a.apk ?

**Comment by aleksejrs** [comment]
Yes, both.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#347
