### ISSUE TITLE
Crash on Import

### ISSUE THREAD

**Issue by dikaio** [kiwix/overview#10]
I've tried to import the wikipedia_en_all_novid_2018-10.zim file I download to my desktop into kiwix but each time I try the app crashes. Any work arounds?

**Comment by kelson42** [comment]
@dikaio which version of Kiwix? which OS?

**Comment by kelson42** [comment]
No feedback, so I'll close the ticket. Please report any pb with Kiwix Desktop here https://github.com/kiwix/kiwix-desktop/issues
