### ISSUE TITLE
Wikipedia descargable sin imágenes 

### ISSUE THREAD

**Issue by DaviidPaez** [kiwix/overview#11]
Pues apenas soy un usuario principiante y viéndola por un tiempo, menor de un mes, me di cuenta que las imágenes eran necesarias, pero no vi una opción de descarga para estas :( 
Y mi opinión es que sería muy util tener una opción en las páginas que diga "Descargar imágenes para esta página (si están disponibles)" pero no sé si haya algo similar o si lo estén pensando para proyectos futuros.

**Comment by Popolechien** [comment]
He says that he did not understand the different files, ended up with the nopic version and would like us to be clearer about what is with/without images. Very much related to what I flagged in [#190](https://github.com/openzim/mwoffliner/issues/190)

**Comment by kelson42** [comment]
@Popolechien thx

**Comment by Popolechien** [comment]
This issue was moved to openzim/mwoffliner#455
