### ISSUE TITLE
Version 2018-11 German novid

### ISSUE THREAD

**Issue by diekarls** [kiwix/overview#14]
Dear Kiwix Team,
I just downloaded the Version 2018-11 (German, novid) by Bitorrent.
Some Articles of this Version do not contain pictures.
Search e.g. for Myanmar, Kuba, Spanien, etc.
This does not happen in Version 2018-06.
Can you provide any idea or help?
Best regards,
Stephan

**Comment by kelson42** [comment]
@diekarls Yes, we believed to haved fixed the bug in the Wikipedia scraper, but we still need to make a new ZIM file

**Comment by kelson42** [comment]
A new version has been released http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2019-08.zim
