### ISSUE TITLE
error reading zim-file header: wikipedia_en_all_novid_2018-10.zim, de_all_novid_2018-06.zim & wikipedia_de_all_novid_2018-11.zim

### ISSUE THREAD

**Issue by kanasethu** [kiwix/overview#16]
I'm running into an error with the following zim files:
 wikipedia_en_all_novid_2018-10.zim
 wikipedia_de_all_novid_2018-06.zim
 wikipedia_de_all_novid_2018-11.zim

The error: ```error reading zim-file header```

Aside: wikipedia_fr_all_novid_2018-10.zim works just fine.

I'm using the linux version of the reader https://download.kiwix.org/bin/kiwix-linux-x86_64.tar.bz2

**Comment by kelson42** [comment]
@kanasethu Thank you for reporting problems to us. If you use Kiwix Desktop 2.0 (still in beta) from https://flathub.org/apps/details/org.kiwix.desktop. I think this should work.

**Comment by kelson42** [comment]
I close the ticket as this is already understodd that old kiwix-xulrunner is not able to deal with new ZIM files.

**Comment by kanasethu** [comment]
@kelson42 I followed the instructions to and downloaded the beta version but ran into Qt errors.   We do not need a full-blown desktop viewer.  All we plan to do is run the kiwix server `bin/kiwix-serve --port=8080 --verbose de.zim`.  Could you give us a skinny build or the command line options to run just the server?

**Comment by kelson42** [comment]
@kanasethu Your command line should work. If you have any problem with `kiwix-serve`. Please check if the problem is not already reported here https://github.com/kiwix/kiwix-tools/issues?q=is%3Aissue+is%3Aopen+label%3Akiwix-serve and otherwise make a bug report.

**Comment by kanasethu** [comment]
@kelson42 
The link you sent me was for `org.kiwix.desktop`?  Can this be run as a server (`kiwix-serve`)?
If so, could you please send details on how to run this executable as a server?
Else if `org.kiwix.desktop` cannot be run as a server, could you please send me a link to a `kiwix-serve` executable which has the fix?

Here is the error I run into:
```
> flatpak run org.kiwix.desktop
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by kelson42** [comment]
@kelson42 The link I have sent to you is about kiwix-tools, not kiwix-desktop.

**Comment by kanasethu** [comment]
@kelson42 How do I get the latest 2.0 build of `kiwix-serve` for linux?

**Comment by kelson42** [comment]
@kanasethu Kiwix-serve does not have the same version numbering like kiwix-desktop. But you can find all binaries at https://download.kiwix.org/release/kiwix-tools/

**Comment by ynikitenko** [comment]
> I close the ticket as this is already understodd that old kiwix-xulrunner is not able to deal with new ZIM files.
@kelson42 could you please tell since when kiwix-xulrunner can't run new ZIM files?
It turned out that I can read wiktionary with the xulrunner, but can't read wikipedia.
