### ISSUE TITLE
iOS11.2 insufficient storage in download section

### ISSUE THREAD

**Issue by Seevo** [kiwix/overview#2]
(as postet in sourceforge)

On an iPhone6sPlus 128GB with 81GB free space and iOS 11.2 (no beta), it is impossible to download any of the 15GB library-packages. They are greyed out leaving me with the message:
“You cannot start downloading, because your device does not have enough free space for this book.”
This is obviously wrong: on the iPhone under settings->info it is stated that there are 81,17GB of free space.

**Comment by kelson42** [comment]
This issue was moved to kiwix/apple#87
