### ISSUE TITLE
Consider using WARC files instead of ZIM files

### ISSUE THREAD

**Issue by traverseda** [kiwix/overview#20]
So it looks to me like WARC files implement *most* of what you want out of the ZIM file format, but there's a healthier third-party ecosystem.

Any thoughts on the possibility of kiwix using WARC files instead of ZIM files some day in the (distant) future?

**Comment by kelson42** [comment]
@traverseda No WARC is not adapted at all to do what we do with ZIM. If you have a doubt, just try to put the whole Wikipedia in English in a WARC file an surf into it on a small device.

**Comment by traverseda** [comment]
Sure, give me some qualifications for what counts as a small device and I'll do a test run. What memory limits? Are there performance profiles for the existing implementation?

**Comment by kelson42** [comment]
RPI O for example

**Comment by traverseda** [comment]
So 512mb of ram? Going by what I've seen of WARC files, that definitely seems doable for warc files, of course you'd want to create those files custom from a dump, not just try and scrape wikipedia.

Do you want to go a bit more depth into the differences between ZIM and WARC that make warc unsuitable?
