### ISSUE TITLE
Publish custom apps “Wikivoyage” and “Chemistry & Physics simulations” in F-Droid

### ISSUE THREAD

**Issue by 4tip** [kiwix/overview#21]
A app called Kiwix, created by “Kiwix Team” is available in F-Droid and I wonder if someone could get two other apps by “Kiwix Team” to the F-Droid repo?? Or release the source code, that F-Droid workers can use to include the apps in F-Droid?
The names of the apps are “Wikivoyage” and “Chemistry & Physics simulations”.

App-Link: https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage 2

App-Link:https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomphet

**Comment by kelson42** [comment]
@4tip The problem is that the FDroid team/software can not deal properly with APK extension files like the Play store does.

**Comment by licaon-kter** [comment]
What are APK extension files? Those OBBs?

**Comment by kelson42** [comment]
Yes

**Comment by kelson42** [comment]
Just to be clear, all Kiwix is FOSS.

**Comment by licaon-kter** [comment]
@eighthave Wasn't OBB support fixed at some point? I'm not aware of its status.

**Comment by eighthave** [comment]
I think OBB support works, but it is not heavily tested.  We welcome bug
reports if anyone finds anything.

**Comment by kelson42** [comment]
I have reopen the ticket. We are willing to help to see this happening. I have moved the ticket to the right repository. But this will tak IMO a bit of time before this will happen except if someone else does the job on the side on Flathub.
