### ISSUE TITLE
Wikipedia(de) 07.08.2019 issue

### ISSUE THREAD

**Issue by DoWenzl94** [kiwix/overview#23]
Hi i am on a iPhone XS 13.1.1 i can't download the newest German Wiki 07.08.2019 (37,02GB) zim, all other are downloading normal. But by this .zim the status remains in "Queued"

![IMG_1734](https://user-images.githubusercontent.com/55977718/65864380-0fa8ac00-e372-11e9-9e14-d7eb832a0824.PNG)

**Comment by kelson42** [comment]
@DoWenzl94 Can you please refresh your list of content, swipe down?

**Comment by DoWenzl94** [comment]
makes no difference

![IMG_1735](https://user-images.githubusercontent.com/55977718/65864941-f3f1d580-e372-11e9-9ebc-4bbdeb3ae643.PNG)

the status is still the same

**Comment by kelson42** [comment]
We have touched that file yesterday... but it should work! Have you tried to stop and restart the download? You can also download the file directly from http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2019-08.zim or via Bittorrent http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2019-08.zim.torrent. I suspect that the problem will solve by itself in a few hours (maybe one day). But you will need to restart the download.

**Comment by DoWenzl94** [comment]
Ok yea i also tried to restart the download, is there any possibility to download the file on the pc and then via cable to the iPhone? i tried now on an fresh installed iPhone 6S, here it is working. So how do you think i can fix it on my XS?

**Comment by kelson42** [comment]
@DoWenzl94 You should be able to copy the file from your mac to your iPhone via iTunes I guess. That should work. But I suspect, if you wait 24 hours, refresh the library and restart the download, it should work. I guess one of the mirror is not up2date.

**Comment by kelson42** [comment]
@DoWenzl94 A few days have passed. Do you still have the problem?

**Comment by DoWenzl94** [comment]
i downloaded the zim to my pc and then to the iphone.
