### ISSUE TITLE
"project guidlines" is a Dead Link in CONTRIBUTING

### ISSUE THREAD

**Issue by kazerthekeen** [kiwix/overview#25]
Under within the [Submitting Code and Documentation Changes](https://github.com/kiwix/overview/blob/master/CONTRIBUTING.md#submitting-code-and-documentation-changes) section of contributing. "Project Guidelines" links to https://github.com/kiwix/overview/blob/master/guidelines/project_guidelines.md which does not exist. 

>We still do not have **project guidelines** for all of the projects hosted in our GitHub Organization, which new repositories should follow during their creation.

Considering the the context it may be purposeful but I would assume in that case that making the text bold would be sufficient.

**Comment by kelson42** [comment]
@kazerthekeen Thx, I have removed the link

**Comment by kazerthekeen** [comment]
Confirmed, Thank you.
