### ISSUE TITLE
Most of the installation links are broken

### ISSUE THREAD

**Issue by mitra42** [kiwix/overview#27]
On https://wiki.kiwix.org/wiki/Software many, if not most of the links are broken 
e.g. 
```
https://download.kiwix.org/bin/kiwix-linux-i686.tar.bz2
https://download.kiwix.org/bin/kiwix-linux-x86_64.tar.bz2
https://download.kiwix.org/bin/kiwix-server-arm.tar.bz2
```
Looking at those links - maybe that's the wrong directory for them ?

**Comment by mitra42** [comment]
Looking further there is https://download.kiwix.org/release/kiwix-tools/ but that has files named by release number, and is missing the https://download.kiwix.org/bin/kiwix-server-arm.tar.bz2

If this isn't going to be fixed for a while, I'd appreciate a quick link to the arm server precompiled binary.

**Comment by kelson42** [comment]
@mitra42 Thank you for reporting this. I have fixed the links. The wiki needs to be revamped. Last refresh was 3-4 years ago and the project had expanded a lot since. Better rely on https://kiwix.org which is better maintained (all the links you were aiming for are properly advertised there).
