### ISSUE TITLE
Consider packaging ZIMs and offline reader as a Web Bundle

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/overview#28]
Having come across https://web.dev/web-bundles/ , Web Bundles look like an ideal technology for packaging ZIM files with a lightweight reader (such as Kiwix JS). Excerpt from the description:

> Web Bundles have multiple unique features:
> 
> * Encapsulates multiple pages, enabling bundling of a complete website into a single file
> * Enables executable JavaScript, unlike MHTML
> * Uses HTTP Variants to do content negotiation, which enables internationalization with the Accept-Language header even if the bundle is used offline
> * Loads in the context of its origin when cryptographically signed by its publisher
> * Loads nearly instantly when served locally
> 
> These features open multiple scenarios. One common scenario is the ability to build a self-contained web app that's easy to share and usable without an internet connection. For example, say you're on an airplane from Tokyo to San Francisco with your friend. You don't like the in-flight entertainment...

**Comment by kelson42** [comment]
@Jaifroid Which problem would that fix? How does that bring an added value to the current setup we have?

**Comment by Jaifroid** [comment]
@kelson42 This is blue-skies thinking. The Web Packaging proposal is "bleeding-edge" and only works behind a flag in Chromium 80+. I just wanted to note this somewhere. Maybe this issue should be moved to Kiwix JS or Kiwix JS Windows. However, it was this that caught my interest

> the ability to build a self-contained web app that's easy to share and usable without an internet connection

No installation, no unzipping, just a bundle that instantly runs, say, WikiMed, when launched.

We can *sort of* do that already with [NWJS WikiMed](https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97N-WikiMed) (but it needs to be unzipped), the UWP WikiMed (needs to be installed) and maybe Kiwix Desktop (needs to be unzipped, but currently no packaged app).

**Comment by kelson42** [comment]
@Jaifroid We can already create this bundles, we have this on Windows (you made it and we have a ticket open I believe to do one with Kiwix-Desktop) on Android (with our custom apps) or on iOS. It works well. So why doing things differently? You think of a package for which platform exactly?

**Comment by Jaifroid** [comment]
This would be compatible with any browser that supports it on any platform. However, it is far too soon for this to be viable, since only one browser supports it currently. I would like to use this issue to track the development of the underlying technology. Are you able to move it to Kiwix JS Windows, @kelson42?

**Comment by kelson42** [comment]
Im not sure there is any actionable with this ticket.... but if you really want it, I can move it.
