### ISSUE TITLE
Regular dumps?

### ISSUE THREAD

**Issue by dcposch** [kiwix/overview#3]
### English wikipedia releases seem to happen irregularly

https://dumps.wikimedia.org/other/kiwix/zim/wikipedia/

```
wikipedia_en_all_2016-05.zim                       17-May-2016 08:17         56911306910
wikipedia_en_all_2016-12.zim                       27-Dec-2016 18:11         62695819637
wikipedia_en_all_nopic_2017-01.zim                 07-Jan-2017 05:05         20180173311
wikipedia_en_all_nopic_2017-08.zim                 14-Sep-2017 10:12         21471834746
wikipedia_en_all_novid_2017-07.zim                 10-Aug-2017 21:33         64048847318
wikipedia_en_all_novid_2017-08.zim                 30-Aug-2017 18:40         64549076329
```

**any chance we could get Kiwix dumps on a regular schedule?**

(eg yearly in january, or quarterly Jan/Apr/Jul/Oct)

**Comment by kelson42** [comment]
We work on that. Goal is to have one per month. That said this is a long process as it does not only imply software solutions or even hardware resources... but also many things like CI, etc. I close the issue as we know the problem, have the vision, work on it but this is probably not going to happen so soon. What should happen soon, is that people won't have to wait a year. Thank you for your patience :)
