### ISSUE TITLE
kiwix 2.0 beta can not open wikipedia_en_all_maxi_2018_10.zim

### ISSUE THREAD

**Issue by yinhaoscu** [kiwix/overview#30]
I have downloaded kiwix-desktop_windows_x64_2.0-rc4 for windows 10, and start kiwix-desktop.exe successfully. However, when I open file wikipedia_en_all_maxi_2018_10.zim, a popup window shows invalid magic number.

**Comment by kelson42** [comment]
@yinhaoscu Your file is corrupted.
