### ISSUE TITLE
Usage as a portable app?

### ISSUE THREAD

**Issue by leethax666** [kiwix/overview#32]
Is it possible to use this on a USB stick or similar as a portable app, with its downloaded wikis and all? It would be really helpful for my emergency USB i keep with my supplies. Thank you!

**Comment by kelson42** [comment]
@leethax666 yes you can, the documentation about how to do that is here https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)
