### ISSUE TITLE
delete my wiki account

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/overview#33]
I created user https://wiki.kiwix.org/wiki/User:Ynikitenko, but then I decided to change the name and created another user.

How the first user (with non-confirmed email) could be deleted? Could you please delete him?

I tried to ask for this in slack, but it wasn't done there. I don't know where else could I ask about that (maybe you should write about that in https://wiki.kiwix.org/wiki/Help? To say where to ask about wiki issues.) Thanks.

**Comment by Popolechien** [comment]
Hola,

Sorry for the late reply. Just like on Wikipedia we cannot delete an account, lest we open the hood and directly mess up with the database (spoiler alert: we don't do that).
I can block the account if you want, but that's about it.

**Comment by ynikitenko** [comment]
Hi, thanks for the reply. Yes, I think it can be blocked. Thanks.
