### ISSUE TITLE
https://wiki.kiwix.org/wiki/Content_in_all_languages Usability problems

### ISSUE THREAD

**Issue by scopulorum** [kiwix/overview#42]
<pre>
1) https://wiki.kiwix.org/wiki/Content_in_all_languages has no link to English 
<img width="1176" alt="Screen Shot 2020-07-08 at 12 01 44" src="https://user-images.githubusercontent.com/68022977/86954237-dd06bd80-c112-11ea-9339-27637d14e7df.png">
2) https://wiki.kiwix.org/wiki/Content_in_all_languages lists many dump permutations but has no searchability, sortability, or way to browse in any organized way. It is a cluttered and awkward user experience.
3) The acronyms don't clearly convey content for new users. Short descriptions would help.
=====
Edit. I now see that the languages section at the top is for the page language, not the dump language. When new users come here for content, this may not be immediately apparent.  
====
https://wiki.kiwix.org/wiki/Content 
  is all english. 
How about creating systematically named and organized pages that are language specific? Or else just an interface to select dump by language, text|vid|pic, content, etc.
=====
The tables are arranged oddly so that the download options are listed above and below the main content row.
</pre>

**Comment by kelson42** [comment]
Yes, this page should be deprecated. We want to transform library.kiwix.org as the future entry point.

**Comment by scopulorum** [comment]
OK. library.kiwix.org still shows way too many entries for a new user to meaningfully parse. I think some organization and structure would be very helpful.

**Comment by kelson42** [comment]
Entry point https://library.kiwix.org allows now filtering and download. Should be used. It fixes this ticket IMO.
