### ISSUE TITLE
Create a kolibri2zim tool

### ISSUE THREAD

**Issue by rgaudin** [kiwix/overview#44]
Following discussion on https://github.com/openzim/warc2zim/issues/48, it would be interesting to create a `kolibri2zim` tool to convert content package made by Learning Equality's Kolibri into ZIM files.

[Kolibri Library](https://catalog.learningequality.org/#/public) already has a lot of interesting content, including Aflatoun and Khan Academy for which our ZIMs are outdated and for which we have no scraper capable of updating.

The technical details for accessing content are detailed on that ticket. Main idea is to use their API to list the available channels and packages. Individual content sets (we will bundle multiple) are offline-friendly media files and custom HTML files.

**Comment by kelson42** [comment]
Development ongoing at https://github.com/openzim/kolibri2zim
