### ISSUE TITLE
Evaluate the time needed to build a mobile version/mobile friendly zim of https://www.teachingenglish.org.uk/

### ISSUE THREAD

**Issue by Popolechien** [kiwix/overview#45]
**Background:** the British Council is looking into distributing an offline app that could help it share resources currently available on its website.

The website is https://www.teachingenglish.org.uk/ It is based off Drupal. 

**Question:** How long would it take to build a scraper and produce a quality zim file of it? Ultimately the content would not be integrated into the Kiwix library but only distributed via a custom app, so it would be rather important that the end product's navigation be similar to that experienced on a mobile device.

Bonus question (I): would it help in building the zim file if we had access to their backend?
Bonus question (II): can we estimate already the size of the corresponding zim file (ballpark figure)?

**Comment by kelson42** [comment]
Actually this is making a ZIM of this
