### ISSUE TITLE
Evaluate the time and effort needed to build a connection to a Whatsapp bot

### ISSUE THREAD

**Issue by Popolechien** [kiwix/overview#46]
**Context:** contact is distributing e-books and examination papers to people in areas with low connectivity (South Africa / Uganda).

He's asked for a zim file (can be done via [Nautilus](../../../openzim/nautilus)) that can either be distributed or also queried via a whatsapp bot (they are using [wati.io](https://www.wati.io/)). The way it's been described the bot would offer a list of contents (files) as menu items, and based on user choice would send the corresponding file in return.

We've seen people [use Kiwix-serve and feed it into a whatsapp bot already](https://www.kiwix.org/en/wikipedia-to-whatsapp-and-circumvent-data-bundles/), though they were using PickyAssist for the whatsapp end of things. Here's their feedback : 
_ "What we did was  fetch content from kiwix server, then remove HTML since WhatsApp doesn't understand that. And then we added the little conveniences like allowing a user to read large pages in small chunks and that about it._

_Really the hard part is getting access to WhatsApp and then building a bot in general. After that, its as easy as adding any other functionality to your bot." _

**Questions**: 
1. assuming we are given access to the wati backend, how much work would be needed to plug Kiwix-serve into their whatsapp bot? 
2. Wouldn't this scenario only make sense if the bot is used to query more than one zim? (e.g. nautilus-based + wikipedia)
3. If we skip the Kiwix-serve part, can we still build it, and how long would it take?

**Comment by kelson42** [comment]
Wati.io is down for the moment, no clue how it works.

**Comment by rgaudin** [comment]
works for me

**Comment by kelson42** [comment]
@Popolechien Should we keep this ticket open?

**Comment by Popolechien** [comment]
Yes please.

**Comment by kelson42** [comment]
@Popolechien Whatbis the perspective here? I‘m not sure to understand where we go.

**Comment by Popolechien** [comment]
@kelson42 that was four years ago and we haven't heard of whatsapp bots becoming a thing, I think we can close this ticket.
