### ISSUE TITLE
2.0-rc3 doesn't work with new zim files

### ISSUE THREAD

**Issue by wgt98** [kiwix/overview#47]
Neither kiwix-desktop.exe nor kiwix-serve in kiwix-desktop_windows_x64_2.0-rc3 work with wikipedia_en_all_maxi_2020-08.zim. Kiwix-serve reports "Unable to add the ZIM file ... to the internal library".

kiwix-serve kiwix-tools_win-i686-3.1.2-3 works fine.

Isn't zim back compatible?

**Comment by kelson42** [comment]
@wgt98 It should work wth the latest version of Kiwix Desktop, version 2.0.4. If not, please make a proper bug report in repository kiwix/kiwix-desktop.
