### ISSUE TITLE
Latest French Wiktionary is posted in wrong directory (Wikipedia instead of Wiktionary)

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/overview#5]
Not sure if this is the right place to post this, but I noticed that the latest French Wiktionary ZIM (01-2018) has been posted to the Wikipedia directory on http://download.kiwix.org/zim/ instead of the Wiktionary directory.

![image](https://user-images.githubusercontent.com/4304337/37018822-b1f7683a-210d-11e8-929e-c0a82679a5ee.png)

**Comment by kelson42** [comment]
@Jaifroid Thx for the bug report.

I have moved the files, fixed the buggy script and restarted library generation.
