### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by mossroy** [kiwix/overview#61]
I would suggest to add a "Code of Conduct" for Kiwix.

We can write our own, or get inspired by existing ones (I don't think we need anything specific to Kiwix), like : 

- https://socratesuk.org/code_of_conduct.html
- https://mixitconf.org/en/codeofconduct

**Comment by kelson42** [comment]
@mossroy Agree and it should probably be the same for the whole project/organisation. I have an old ticket to even syncrhonise this file on each code repo, see https://github.com/kiwix/maintenance/issues/152

**Comment by mossroy** [comment]
Good idea!
