### ISSUE TITLE
Scraping of German Wiktionary not working correctly (missing photos & translations)

### ISSUE THREAD

**Issue by GPLv3-fan** [kiwix/overview#64]
The German Wiktionary is not being scraped properly. The code to scrape the German Wiktionary fails to obtain many photos and translations.

For example, the .zim version from February 2022 shows the headword "schütten" without any photo:

![image](https://user-images.githubusercontent.com/58692066/161354546-04ab77da-0b56-4345-97dc-ac79e125cfb6.png)

However, the online version shows a photo that was added to the Wiki on November 3, 2021:

![image](https://user-images.githubusercontent.com/58692066/161354729-4ce68a5f-8836-44ca-aa43-686fbe28568d.png)

![image](https://user-images.githubusercontent.com/58692066/161354689-192c118f-230a-4b70-80f8-26331035af7a.png)

Therefore, the "February" .zim did not include a photo that was already there. I tried the Kiwix App on Android and GoldenDict. The image is simply missing. That issue is relatively common in the German Wiktionary. The same happens with the Translations Box.

**_It seems that the code to scrape the German Wiktionary needs to be updated/improved._** 

Thanks for your hard work ! :D

**Comment by kelson42** [comment]
@GPLv3-fan Which ZIM file exactly have you downloaded?

**Comment by GPLv3-fan** [comment]
@kelson42  I am not sure about how to report his bug properly to Wikimedia Headquarters. I have doubts about the proper category and the technical details (I am not  a programmer).  **Could you please kindly report the bug with technical information to Wikimedia ?**

_I collected several links with the issue of lacking images on .zim files that are present on the German Wiktionary:_
https://de.wiktionary.org/wiki/Fensterbrett
https://de.wiktionary.org/wiki/schütten
https://de.wiktionary.org/wiki/riechen
https://de.wiktionary.org/wiki/parken
https://de.wiktionary.org/wiki/ernten

_3 photos on Wiktionary and 2 missing:_
https://de.wiktionary.org/wiki/balancieren
