### ISSUE TITLE
English Wiktionary is not listed properly (different date and name)

### ISSUE THREAD

**Issue by ghost** [kiwix/overview#68]
The English Wiktionary (all maxi) has 2 problems:
https://wiki.kiwix.org/wiki/Content_in_all_languages

![grafik](https://user-images.githubusercontent.com/58692066/172072664-011414fd-7bef-45b5-90ca-3c8d27a1c0ca.png)

**1) Date seems incorrect:** updated on 2022-02.

I downloaded on Feb. 17th the 2022-02 version, and the SHA256 is different from the version offered online today. Clearly, they are not the same files.

SHA256 2022-02 in my SSD  _e999e05eb6f3e5a532b27eb9faf594cca62be1c22788c4faad1d147ec33a4b5a_
SHA256 2022-02 offered online:  _2c4c01f8e71360019b966f3b556b3a1edd0df1ccff879142e7b4ecf4a246fb2a_

The copy in my SSD works perfectly on GoldenDict. My file is not corrupted.

**2) Size difference:** 
The version from 2022-02 in my hard drive is 6.1 GiB while the version offered online has different file size. So,  the version offered online definitely is not from 2022-02.

-----------
I believe that the English Wiktionary (all maxi) offered online is from 2022-05, but is being described as 2022-02. 

**Could someone confirm the issue and correct the listing problem?** 

Might need correction: Date of scraping and filename itself.

_Thanks for your great job ! :D_

**Comment by kelson42** [comment]
> I downloaded on Feb. 17th the 2022-02 version, and the SHA256 is different from the version offered online today. Clearly, they are not the same files.

Difficult to say as the file is not delivered anymore but I strongly suspect your ZIM file is corrupted. The tool `zimcheck` could tell you (available in the zim-tools),
