### ISSUE TITLE
Gutenberg Project CD(-sized) set

### ISSUE THREAD

**Issue by run-dey** [kiwix/overview#7]
I see that this page is being used for data issues.

There is a complete set of English Gutenberg books on kiwix.org, which is great, but it is also prohibitively big (50+ GB).

But there has also been released a 'best of' Gutenberg CD. It would be a great option for smaller devices, and would certainly be appreciated by many people.

http://www.gutenberg.org/wiki/Gutenberg%3AThe_CD_and_DVD_Project

I would have made the ZIM file myself from the HTML/text files, but unfortunately I am not in the position to do so at the moment.

Thank you.

Sent from a disposable GitHub account.

**Comment by kelson42** [comment]
This issue was moved to openzim/gutenberg#61
