### ISSUE TITLE
Installer fails but first wastes an hour of the user's time

### ISSUE THREAD

**Issue by scottmayo** [kiwix/overview#70]
Run the installer and answer a lot of questions. Spend an hour researching and selecting static content to fill a 256G SD.
Run installation. 
It fails because it cannot find exfat-utils, and I don't even know why it needs it - the SD is already clean. When you choose abort, the whole application exits, and _none of your settings are saved_.

Check your preconditions BEFORE you waste an hour of the user's time sorting through a disorganized list of hundreds of topics. 

Also, there would be a way to build an image from .zim files I've already downloaded, and it would be way nicer if you could copy zim files onto the boot disk and have the server find them. Having to build them into the image makes no sense and causes a lot of effort if you just want to add something.

**Comment by kelson42** [comment]
I guess this is a ticket for kiwix-hotspot repository.

**Comment by kelson42** [comment]
Moved to https://github.com/offspot/kiwix-hotspot/issues/661
