### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by nyr95** [kiwix/overview#86]
Hi I am Nagraj Y R, 3rd year CSE student.
My question is on the submission of the proposal.
I want to ask How exactly do I submit my proposal?
Do I have to make changes in the code and then send a PR ?
Or Do I just have to explain the steps of solving in a proposal PDF?
I am a seasoned web developer having developed UI for motion sensing app,etc.
I would like you to please accept my proposal for working on this wonderful project

**Comment by rgaudin** [comment]
Please read the GSoC documentation.
